---
# tasks file for raspberrypi_headless

- name: identify boards
  command: grep "^Model" /proc/cpuinfo
  register: board_model

- name: print board model
  debug: var=board_model.stdout

- import_tasks: disable-audio.yml
  tags:
  - audio

- import_tasks: disable-swap.yml
  tags:
  - swap

- import_tasks: tmpfs.yml
  tags:
  - tmpfs

- import_tasks: locale.yml
  tags:
  - locale

- import_tasks: timezone.yml
  tags:
  - timezone

- import_tasks: hostname.yml
  tags:
  - hostname

